
import dotenv from 'dotenv';
dotenv.config();

const JWT_USER_PASSWORD= process.env.JWT_USER_PASSWORD;
const JWT_ADMIN_PASSWORD= process.env.JWT_ADMIN_PASSWORD;
const STRIPE_SECRET_KEY="sk_test_51ReCu2DCLk52beDiC3dFWDVeMrirP76PQ32srsgc4KE1MhI4W5WqPVVQePTnYAd0okHkGtvF057LYYndoiaMvVOM00Tp3EguMd";


export default {JWT_USER_PASSWORD,JWT_ADMIN_PASSWORD,STRIPE_SECRET_KEY};